CREATE DATABASE AcessoryHub;

USE AcessoryHub;

CREATE TABLE Lojas(
	Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Dono VARCHAR(100) NOT NULL,
    Endereco VARCHAR(200) NOT NULL UNIQUE,
    Telefone VARCHAR(16) NOT NULL UNIQUE,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Estado VARCHAR(20) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Cnpj VARCHAR(20) NOT NULL UNIQUE,
    Data_Abertura DATE NOT NULL,
    Status VARCHAR(10) NOT NULL
);